#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 12 14:17:25 2022

@author: lisboa
"""
#importação de sempre
        import pandas as pd
        import numpy as np
        from keras.models import Sequential
        from keras.layers import Dense, Dropout

#entrada de sempre
        previsores = pd.read_csv('entradas_breast.csv')
        classe = pd.read_csv('saidas_breast.csv')

#cria normalmente a rede neural e com base dos testes realizados com o tuning e a validação cruzada
# colocaremos os paramentros que melhor se destacaram
        classificador = Sequential()
        classificador.add(Dense(units= 8, activation= 'relu',
                                kernel_initializer= 'normal', input_dim= 30))
        classificador.add(Dropout(0.2))
        classificador.add(Dense(units= 8, activation= 'relu',
                                kernel_initializer= 'normal'))
        classificador.add(Dropout(0.2))
        classificador.add(Dense(units= 1, activation= 'sigmoid'))
        classificador.compile(optimizer= 'adam', loss= 'binary_crossentropy',
                            metrics= ['binary_accuracy'])
        classificador.fit(previsores, classe, batch_size= 10, epochs= 100)

#aqui fica a entrada de um novo dado, supondo aqui que foi analizado um paciente com suspeita
# e seu médico se utilizou da rede para avaliar e tomar uma decisão
        novo = np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                        0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                        0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                        0.84, 158, 0.363]])

#rodando o dado novo na rede neural
        previsao = classificador.predict(novo)
#exibindo entre true ou false, onde acima de 50% se torna true,
# dependendo do caso esse valor é alterado
        previsao = (previsao > 0.5)
